---

- hosts: localhost
  connection: local
  become: true
  vars:
      is_container: true

  roles:
  - role: "{{ playbook_dir }}"
    rhel8cis_system_is_container: "{{ is_container | default(false) }}"
    rhel8cis_skip_for_travis: false
